Repository akelsch/spring-reactive-chat, pull requests merged in 2019-03, with the labels that each got.

#22 Todos
  README.md
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/de/htwsaar/vs/chat/ChatApplication.java
  src/main/java/de/htwsaar/vs/chat/Init.java
  src/main/java/de/htwsaar/vs/chat/auth/ChatAuthority.java
  src/main/java/de/htwsaar/vs/chat/auth/Role.java
  src/main/java/de/htwsaar/vs/chat/auth/UserPrincipal.java
  src/main/java/de/htwsaar/vs/chat/auth/WebSecurity.java
  src/main/java/de/htwsaar/vs/chat/auth/jwt/JwtAuthenticationConverter.java
  src/main/java/de/htwsaar/vs/chat/auth/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/de/htwsaar/vs/chat/auth/jwt/JwtAuthorizationConverter.java
  src/main/java/de/htwsaar/vs/chat/configuration/SecurityConfiguration.java
  src/main/java/de/htwsaar/vs/chat/handler/AuthHandler.java
  src/main/java/de/htwsaar/vs/chat/handler/ChatHandler.java
  src/main/java/de/htwsaar/vs/chat/handler/MessageHandler.java
  src/main/java/de/htwsaar/vs/chat/handler/UserHandler.java
  src/main/java/de/htwsaar/vs/chat/model/BaseDocument.java
  src/main/java/de/htwsaar/vs/chat/model/Chat.java
  src/main/java/de/htwsaar/vs/chat/model/Message.java
  src/main/java/de/htwsaar/vs/chat/model/Password.java
  src/main/java/de/htwsaar/vs/chat/model/User.java
  src/main/java/de/htwsaar/vs/chat/model/serializer/CollectionSizeSerializer.java
  src/main/java/de/htwsaar/vs/chat/model/serializer/DocumentIdSerializer.java
  src/main/java/de/htwsaar/vs/chat/repository/ChatRepository.java
  src/main/java/de/htwsaar/vs/chat/router/ChatRouter.java
  src/main/java/de/htwsaar/vs/chat/router/UserRouter.java
  src/main/java/de/htwsaar/vs/chat/service/ChatService.java
  src/main/java/de/htwsaar/vs/chat/service/MessageService.java
  src/main/java/de/htwsaar/vs/chat/service/UserService.java
  src/main/java/de/htwsaar/vs/chat/util/CollectionUtils.java
  src/main/java/de/htwsaar/vs/chat/util/JwtUtils.java
  src/main/java/de/htwsaar/vs/chat/util/ResponseUtils.java
Labels: bug, enhancement

#23 Tests
  build.gradle.kts
  src/it/java/de/htwsaar/vs/chat/AuthIntegrationTests.java
  src/it/java/de/htwsaar/vs/chat/UserIntegrationTests.java
  src/it/resources/application.properties
  src/main/java/de/htwsaar/vs/chat/ChatApplication.java
  src/main/java/de/htwsaar/vs/chat/configuration/MongoConfiguration.java
  src/main/java/de/htwsaar/vs/chat/handler/ChatHandler.java
  src/main/java/de/htwsaar/vs/chat/handler/UserHandler.java
  src/test/java/de/htwsaar/vs/chat/ChatApplicationTest.java
  src/test/java/de/htwsaar/vs/chat/DisableCsrfSecurityConfiguration.java
  src/test/java/de/htwsaar/vs/chat/DisableWebFluxSecurityCsrf.java
  src/test/java/de/htwsaar/vs/chat/handler/AuthHandlerTests.java
  src/test/java/de/htwsaar/vs/chat/service/UserServiceTests.java
  src/test/resources/application.properties
Labels: enhancement, help wanted

#27 Exception handling on a global level
  src/main/java/de/htwsaar/vs/chat/auth/jwt/JwtAuthenticationConverter.java
  src/main/java/de/htwsaar/vs/chat/auth/jwt/JwtAuthorizationConverter.java
  src/main/java/de/htwsaar/vs/chat/error/CustomErrorAttributes.java
  src/main/java/de/htwsaar/vs/chat/handler/AuthHandler.java
  src/main/java/de/htwsaar/vs/chat/handler/ChatHandler.java
  src/main/java/de/htwsaar/vs/chat/handler/UserHandler.java
  src/main/java/de/htwsaar/vs/chat/util/ResponseUtils.java
Labels: enhancement

#28 Update user roles
  src/it/java/de/htwsaar/vs/chat/UserIntegrationTests.java
  src/main/java/de/htwsaar/vs/chat/handler/UserHandler.java
  src/main/java/de/htwsaar/vs/chat/model/Role.java
  src/main/java/de/htwsaar/vs/chat/router/UserRouter.java
  src/main/java/de/htwsaar/vs/chat/service/MessageService.java
  src/main/java/de/htwsaar/vs/chat/service/UserService.java
  src/test/java/de/htwsaar/vs/chat/service/UserServiceTests.java
Labels: enhancement

#33 Stream new chats
  src/main/java/de/htwsaar/vs/chat/configuration/SecurityConfiguration.java
  src/main/java/de/htwsaar/vs/chat/handler/ChatHandler.java
  src/main/java/de/htwsaar/vs/chat/router/ChatRouter.java
  src/main/java/de/htwsaar/vs/chat/service/ChatService.java
  src/main/java/de/htwsaar/vs/chat/service/MessageService.java
  src/main/java/de/htwsaar/vs/chat/util/SecurityUtils.java
Labels: enhancement

#34 Profil status
  build.gradle.kts
  src/it/java/de/htwsaar/vs/chat/AuthIntegrationTests.java
  src/it/java/de/htwsaar/vs/chat/UserIntegrationTests.java
  src/main/java/de/htwsaar/vs/chat/handler/UserHandler.java
  src/main/java/de/htwsaar/vs/chat/model/User.java
  src/main/java/de/htwsaar/vs/chat/model/sub/Password.java
  src/main/java/de/htwsaar/vs/chat/model/sub/Role.java
  src/main/java/de/htwsaar/vs/chat/model/sub/Status.java
  src/main/java/de/htwsaar/vs/chat/router/UserRouter.java
  src/main/java/de/htwsaar/vs/chat/service/UserService.java
  src/test/java/de/htwsaar/vs/chat/handler/AuthHandlerTests.java
Labels: enhancement
