Repository akelsch/spring-reactive-chat, pull requests merged in 2019-02, with the labels that each got.

#14 Filter imp
  src/main/java/de/htwsaar/vs/chat/handler/UserHandler.java
Labels: enhancement, good first issue

#15 Develop
  src/main/java/de/htwsaar/vs/chat/handler/ChatHandler.java
  src/main/java/de/htwsaar/vs/chat/handler/MessageHandler.java
  src/main/java/de/htwsaar/vs/chat/model/Chat.java
  src/main/java/de/htwsaar/vs/chat/model/Message.java
  src/main/java/de/htwsaar/vs/chat/model/User.java
  src/main/java/de/htwsaar/vs/chat/repository/ChatRepository.java
  src/main/java/de/htwsaar/vs/chat/repository/MessageRepository.java
  src/main/java/de/htwsaar/vs/chat/router/ChatRouter.java
  src/main/java/de/htwsaar/vs/chat/service/ChatService.java
  src/main/java/de/htwsaar/vs/chat/service/MessageService.java
Labels: enhancement

#16 Change password
  src/main/java/de/htwsaar/vs/chat/handler/UserHandler.java
  src/main/java/de/htwsaar/vs/chat/model/Password.java
  src/main/java/de/htwsaar/vs/chat/router/UserRouter.java
  src/main/java/de/htwsaar/vs/chat/service/UserService.java
Labels: enhancement, good first issue

#18 Cors dev prod
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/de/htwsaar/vs/chat/configuration/SecurityConfiguration.java
  src/main/resources/application-prod.properties
  src/test/resources/application.properties
Labels: bug
